#!/usr/bin/env bash
#Bash script that displays Best School 10 times
#but for the 9th iteration, displays Best School
#and then Hi on a new line.
str=1
while [ $str -le 10 ]
do
echo "Best School"
if [ $str -eq 9 ]
then
echo "Hi"
fi
((str++))
done
