#!/usr/bin/env bash
#Bash script that loops from 1 to 10
str=1
while [ $((str++)) -le 10 ]
do
	if [ $str -eq 4 ]
	then
		echo "bad luck"
	elif [ $str -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	done
